name: autohub
description: "Simple Testing Project"

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pin_code_fields: ^8.0.1
  curved_navigation_bar: ^1.0.3
  shared_preferences: ^2.2.2
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo-SemiBoldItalic.ttf
          weight: 700

    - family: Archivo_Condensed
      fonts:
        - asset: assets/fonts/Archivo-SemiBold.ttf
    - family: Archivo_ECondensed
      fonts:
        - asset: assets/fonts/Archivo_ExtraCondensed-Black.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_regular.ttf
    - family: Hegarty
      fonts:
        - asset: assets/fonts/hegarty_regular.ttf
#
#    - family: Source Sans
#      fonts:
#        - asset: assets/fonts/source_sans_regular.ttf


